language: ruby
rvm:
- 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
branches:
  only:
  - master
install:
- bundle install
script:
- bundle exec jekyll build
- timeout 240s bundle exec htmlproofer ./_site --check-html --check-favicon --allow-hash-href
  --external_only --only-4xx --http-status-ignore 429
after_success: s3_website push
notifications:
  slack:
    rooms:
      - secure: gl5fJQSzjEVH5Q3Q3D5eK3xBEB14bgaA9+Ma0AklTblzES6o4wlPAMfsyu7+ofyF3b4iiTfG/Og67JklYoTwk2aO/8/xJyiUhJArsC362klVhdCPSibbji9buDgrSVOg8ZAZ8uDmITwlpyU4OJ4/SrdeyoIVKmFrVqfuGlnUL4UTCdJZhFfrB9liyc2uIvsuajn8azQEKxBRX0KOP2zNhiEmaQfg16t4UmUUPAyXFOOBczjv584JObxA5Qzj2eNsnRQyj7TtPVbsStZJapf4p8Cv/jI3p9uujuajzXR3xsqV05y1MWC4ZevRP47CdPJJmf/M0LJV2TwlMA0oi8UbVqZdJdJBRgZuLEBNiNwN/i8t6rm+WQX3lTuh13wsNC725Hs9EBx8huPoD1eAZjO56tNq3UkxxgiQ91h958HwSU3no8KnAV0faV9wr7o+Uyg9nLbyFHE5eU66AsoS9KQyKe24hPoTzcXTyEiJvoKy50URa8kDRZoI0Y2WY+hhIllpJZGbnpHEAV9VhY0XfP1P2hpVJXAgZDTwW3OrrJqDL+1DBalvkdZajzJKu8vPcBXu2qrQ2/6BSr3BKekXX+t0alyUsQyqnEpA+uwXH0BW6Ujw9HXMfIu1XxVYdX9iiK76dBkuKm0LjHsxyzdz/GnEfd8N9nxhcI7792ilzhlL8ko=
    on_success: always
